version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "open"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/app"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/common"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/network"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/vendor"
    schedule:
      interval: "daily"